bin/program: obj/main.o obj/server.o
	gcc -o bin/program obj/main.o obj/server.o

obj/main.o: main.c
	gcc -o obj/main.o main.c

obj/server.o: server.c
	gcc -0 obj/server.o server.c

clean:
	rm -rf obj/*.o bin/program